### ISSUE TITLE
If user is in the same server/channel multiple times, they display messages multiple times.

### ISSUE THREAD

**Issue by nt-complete** [technicallyerik/WIRK#37]

**Comment by technicallyerik** [comment]
If you update, I temporary created a fix that doesn't let you join the same server multiple times in the first place :)

The issue is we key everything by the server host name, so a 'better' fix will at some point to figure out a way to uniquely identify multiple instances of the same server.  I think there is another ticket somewhere for that.

**Comment by nt-complete** [comment]
Isaac's idea was IDing on the server name & local port (which should be unique).

**Comment by technicallyerik** [comment]
Yeah I don't even know if this is a problem anymore.  I re factored a bunch of things to pass server around as the object instead of by name.  I opened #38 to investigate.
